global using Microsoft.AspNetCore.Mvc;
global using ServiciosGrupoMundial.TechnicalTest.BusinessLogic;
global using ServiciosGrupoMundial.TechnicalTest.BusinessLogic.Services;
global using ServiciosGrupoMundial.TechnicalTest.BusinessObjects.POCOs;
global using ServiciosGrupoMundial.TechnicalTest.BusinessObjects.ValueObjects;